"""empty message

Revision ID: 3481c85ebb7b
Revises: 3e63efedb0f6
Create Date: 2025-09-29 17:07:17.225480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3481c85ebb7b'
down_revision = '3e63efedb0f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('push_subscription', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('push_subscription')

    # ### end Alembic commands ###
