"""init

Revision ID: 3e63efedb0f6
Revises: 546b8c35016f
Create Date: 2025-09-28 18:09:33.037733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e63efedb0f6'
down_revision = '546b8c35016f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
